name: fluffboost
services:
  postgres:
    image: 'postgres:16-alpine'
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluffboost
    ports:
      - '5432:5432'
    volumes:
      - 'fluffboost-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
        - '-d'
        - fluffboost
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'fluffboost-redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 30s
      retries: 5

volumes:
  fluffboost-postgres-data:
  fluffboost-redis-data:
